### ISSUE TITLE
ADC Timeout while running rabihigh

### ISSUE THREAD

**Issue by btchiaro** [martinisgroup/servers#252]
At least one other user is not effected by this problem.  
```
In [1]: sq.rabihigh(s,'q4')
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-1-3f0f34616f76> in <module>()
----> 1 sq.rabihigh(s,'q4')

/home/ben/pyleBen/pyle/pyle/dataking/singleQubit.pyc in rabihigh(Sample, measure, name, amps, alpha, state, numPulses, stats, IQ, mode, correct, save, collect, noisy, update, manual)
   1779             returnValue(np.squeeze(prob))
   1780 
-> 1781     data = sweeps.grid(func, axes, dataset=dataset, save=save, noisy=False)
   1782 
   1783     if update and manual:

/home/ben/pyleBen/pyle/pyle/dataking/sweeps.pyc in grid(func, axes, dataset, **kw)
    320         dataset=dataset,
    321         abortPrefix=[1],
--> 322         **kw
    323     )
    324 

/home/ben/pyleBen/pyle/pyle/dataking/sweeps.pyc in _run(func, sweep, save, dataset, abortable, abortPrefix, collect, noisy, pipesize)
    219         params = dataset.params
    220         name = dataset.name
--> 221         data = np.vstack(it)
    222         kwargs = {'number': dataset.num, 'path': dataset.path} if save else {}
    223         return pyle.datavault.LocalDataSet(data, independents, dependents,

/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.pyc in vstack(tup)
    226 
    227     """
--> 228     return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
    229 
    230 def hstack(tup):

/home/ben/pyleBen/pyle/pyle/datasaver.pyc in capture(self, iterable)
    146         """
    147         with self as dataset:
--> 148             for data in iterable:
    149                 dataset.add(data)
    150                 yield data

/home/ben/pyleBen/pyle/pyle/pipeline.pyc in gen()
     99             runners.append(runner)
    100             if len(runners) >= size:
--> 101                 done, result = advance()
    102                 if done:
    103                     yield result

/home/ben/pyleBen/pyle/pyle/pipeline.pyc in advance()
     80             # loop over runners, advancing until one completes
     81             for runner in itertools.cycle(runners):
---> 82                 runner.advance()
     83                 if runner.done:
     84                     break

/home/ben/pyleBen/pyle/pyle/pipeline.pyc in advance(self)
    123         if not self.done:
    124             try:
--> 125                 self.gen.next()
    126             except _DefGen_Return, e:
    127                 self.done = True

/home/ben/pyleBen/pyle/pyle/pipeline.pyc in _run(gen)
    173             elif is_generator(result):
    174                 try:
--> 175                     for _ in _run(result):
    176                         yield
    177                     result = None

/home/ben/pyleBen/pyle/pyle/pipeline.pyc in _run(gen)
    170                     result = result.wait()
    171                 except Exception, e:
--> 172                     result = gen.throw(e)
    173             elif is_generator(result):
    174                 try:

/home/ben/pyleBen/pyle/pyle/dataking/singleQubit.pyc in func(amp)
   1771 
   1772         if IQ:
-> 1773             data = yield Sample.run(alg, stats, dataFormat='iqRaw')
   1774             I,Q = readout.averageIQSingleDemod(data)
   1775             returnValue([I,Q])

Error: (0) java.util.concurrent.ExecutionException: org.labrad.errors.LabradException: [GHz FPGAs] Remote Traceback (most recent call last):
  File "C:\pylabrad\labrad\server.py", line 262, in handleRequest
    result = yield setting.handleRequest(self, c.data, data)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1097, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "ghz_fpga_server.py", line 1491, in run_sequence
    timingOrder)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "ghz_fpga_server.py", line 744, in run
    raise TimeoutError(self.timeoutReport(runners, results))
__main__.TimeoutError: Some boards failed:
Vince DAC 14: OK Expected executions: 600  Actual: 0
Vince DAC 17: OK Expected executions: 600  Actual: 0
Vince DAC 12: OK Expected executions: 600  Actual: 0
Vince DAC 11: OK Expected executions: 600  Actual: 0
Vince DAC 27: OK Expected executions: 600  Actual: 0
Vince DAC 13: OK Expected executions: 600  Actual: 0
Vince DAC 24: OK Expected executions: 600  Actual: 0
Vince ADC 1: timeout! Expected executions: 600  Actual: 49
Vince DAC 26: OK Expected executions: 600  Actual: 0
Vince DAC 16: OK Expected executions: 600  Actual: 0

	at org.labrad.RequestReceiver.get(RequestReceiver.java:111)
	at org.labrad.RequestReceiver.get(RequestReceiver.java:41)
	at org.labrad.ServerConnection.sendAndWait(ServerConnection.java:526)
	at org.labrad.qubits.QubitContext.run_experiment(QubitContext.java:1106)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.labrad.handlers.SingleArgVoidHandler.handle(SingleArgVoidHandler.java:24)
	at org.labrad.ContextManager.processRequest(ContextManager.java:143)
	at org.labrad.ContextManager.access$100(ContextManager.java:15)
	at org.labrad.ContextManager$RequestProcessor.run(ContextManager.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.labrad.errors.LabradException: [GHz FPGAs] Remote Traceback (most recent call last):
  File "C:\pylabrad\labrad\server.py", line 262, in handleRequest
    result = yield setting.handleRequest(self, c.data, data)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1097, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "ghz_fpga_server.py", line 1491, in run_sequence
    timingOrder)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "ghz_fpga_server.py", line 744, in run
    raise TimeoutError(self.timeoutReport(runners, results))
__main__.TimeoutError: Some boards failed:
Vince DAC 14: OK Expected executions: 600  Actual: 0
Vince DAC 17: OK Expected executions: 600  Actual: 0
Vince DAC 12: OK Expected executions: 600  Actual: 0
Vince DAC 11: OK Expected executions: 600  Actual: 0
Vince DAC 27: OK Expected executions: 600  Actual: 0
Vince DAC 13: OK Expected executions: 600  Actual: 0
Vince DAC 24: OK Expected executions: 600  Actual: 0
Vince ADC 1: timeout! Expected executions: 600  Actual: 49
Vince DAC 26: OK Expected executions: 600  Actual: 0
Vince DAC 16: OK Expected executions: 600  Actual: 0

	at org.labrad.RequestReceiver.set(RequestReceiver.java:171)
	at org.labrad.RequestDispatcher.finishRequest(RequestDispatcher.java:89)
	at org.labrad.ServerConnection.handlePacket(ServerConnection.java:587)
	at org.labrad.ServerConnection.access$100(ServerConnection.java:77)
	at org.labrad.ServerConnection$1.run(ServerConnection.java:314)
	... 1 more
 [payload=None]
```

**Comment by maffoo** [comment]
The problem seems to have been due to a large bias settling time, and the timeout was not being calculated properly for the sequence being executed.
