### ISSUE TITLE
when qubit sequencer has conflicting microwave configurations, tell me _what_ the conflict is

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#272]
The following error message came from the qubit sequencer:

```
Error: (0) java.lang.IllegalArgumentException: requirement failed: Conflicting microwave configurations for source 'Vince GPIB Bus - GPIB0::4::INSTR'
	at scala.Predef$.require(Predef.scala:219)
	at org.labrad.qubits.QubitContext$$anonfun$build_sequence$1.apply(QubitContext.scala:934)
	at org.labrad.qubits.QubitContext$$anonfun$build_sequence$1.apply(QubitContext.scala:923)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.labrad.qubits.QubitContext.build_sequence(QubitContext.scala:923)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.labrad.handlers.ZeroArgVoidHandler.handle(ZeroArgVoidHandler.java:16)
	at org.labrad.ContextManager.processRequest(ContextManager.java:143)
	at org.labrad.ContextManager.access$100(ContextManager.java:15)
	at org.labrad.ContextManager$RequestProcessor.run(ContextManager.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
 [payload=None]
```

It would be more useful if were to give information on the conflict.

**Comment by pomalley** [comment]
Well, it's either the frequency or the power, right?

seriously though, it would be good to provide more detail. Also it's not particularly helpful to tell me the GPIB address--the qubits are what I know how to deal with.
