### ISSUE TITLE
Error message from qubit server if boards don't exist is misleading

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#305]
If I don't turn on the direct ethernet server, but start everything else, and then try to run an experiment, I get a failure from the qubit server saying

```
java.lang.RuntimeException: Cannot assign jump table commands to memory board Vince DAC 13
	at scala.sys.package$.error(package.scala:27)
	at org.labrad.qubits.FpgaModelDac.getJumpTableController(FpgaModelDac.scala:94)
	at org.labrad.qubits.Experiment$$anonfun$addJumpTableEntry$1.apply(Experiment.scala:250)
	at org.labrad.qubits.Experiment$$anonfun$addJumpTableEntry$1.apply(Experiment.scala:249)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at org.labrad.qubits.Experiment.addJumpTableEntry(Experiment.scala:249)
	at org.labrad.qubits.QubitContext.jump_table_add_entry(QubitContext.scala:517)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.labrad.handlers.MultiArgVoidHandler.handle(MultiArgVoidHandler.java:32)
	at org.labrad.ContextManager.processRequest(ContextManager.java:143)
	at org.labrad.ContextManager.access$100(ContextManager.java:15)
	at org.labrad.ContextManager$RequestProcessor.run(ContextManager.java:181)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

It would be more clear to say something about the board simply not existing.

**Comment by pomalley** [comment]
Yes, the way the qubit sequencer works is that if it fails to ping a board it gives it a default build number. This is totally wrong, but I think it does it this way because it needs to match the wiring key. We should probably fix this.
