### ISSUE TITLE
SuperMonitor has matplotlib deprecation warning

### ISSUE THREAD

**Issue by jwenner** [martinisgroup/servers#359]
When I start the SuperMonitor on a computer with matplotlib 1.4.0 and master commit aa874862cddb015e5fe2ac36af44df5862983d72, I get the following matplotlib deprecation warning:
```
Found node_ivan, using directory Ivan
DR Logger running
C:\Python27\lib\site-packages\matplotlib\backends\backend_qt5agg.py:210: Matplot
libDeprecationWarning: This class has been deprecated in 1.4 as it has no additi
onal functionality over `NavigationToolbar2QT`.  Please change your code to use
`NavigationToolbar2QT` instead
  mplDeprecation)
```

**Comment by jwenner** [comment]
Note that for matplotlib 1.5.0 (haven't tested for 1.4.1-1.4.3), trying to run the SuperMonitor gives the following error:
```
C:\Code\servers\GUIs>SuperMonitor.py
Traceback (most recent call last):
  File "C:\Code\servers\GUIs\SuperMonitor.py", line 14, in <module>
    from LabRADPlotWidget3 import LabRADPlotWidget3
  File "C:\Code\servers\GUIs\LabRADPlotWidget3.py", line 8, in <module>
    from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as Na
vigationToolbar
ImportError: cannot import name NavigationToolbar2QTAgg
```
