### ISSUE TITLE
GPIB server issue with PNA_X server

### ISSUE THREAD

**Issue by thchwhite** [martinisgroup/servers#422]
`
[PNA_X] Remote Traceback (most recent call last):
Failure: labrad.types.types.Error: (0) [pfeiffer-lab GPIB Bus] Remote Traceback (most recent call last):
  File "/usr/local/labrad/pyle/labrad/server.py", line 255, in request_handler
    c.data, flat_data)
  File "/usr/local/labrad/pyle/labrad/server.py", line 216, in _dispatch
    return func(*args, **kw)
  File "/usr/local/labrad/pyle/labrad/decorators.py", line 200, in handleRequest
    return self.func(server, c, data)
  File "gpib_server.py", line 293, in read
    return ans.decode('utf-8').strip()
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xbf in position 7: invalid start byte
 [payload=None]
 [payload=None]
'

**Comment by maffoo** [comment]
We're probably doing a read that should be read_raw.

**Comment by thchwhite** [comment]
At some point I believe this got fixed in the GPIB server.  Its possible the commit was never pushed though.

**Comment by kunalq** [comment]
Closing, as this is related to another repo. :)
