### ISSUE TITLE
ghz_fpgas.dac_leds doesn't work

### ISSUE THREAD

**Issue by cjneill** [martinisgroup/servers#69]
When we try ghz_fpgas.dac_leds, it spits out an error about not finding 'I2C_RB' (see error message below). On master branch.

```
In [6]: f.dac_leds(170)
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)

C:\Windows\system32\<ipython console> in <module>()

C:\pylabrad\labrad\client.pyc in __call__(self, *args, **kw)
     62         if wrap:
     63             future.addCallback(lambda resp: resp[0][1])
---> 64         return future.wait() if wait else future
     65
     66     # data to be loaded on demand


C:\pylabrad\labrad\backend.pyc in wait(self)
    397                 # If any Future in the queue fails,

    398                 # we immediately bail.

--> 399                 result.raiseException()
    400             else:
    401                 for func, args, kw in f.callbacks:

C:\Python26\lib\site-packages\twisted\python\failure.pyc in raiseException(self)

    324         information if available.
    325         """
--> 326         raise self.type, self.value, self.tb
    327
    328

Error: (0) [GHz FPGAs] Remote Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1107, in
_inlineCallbacks
    result = g.send(result)
  File "C:\pylabrad\servers\GHzDACs\Cleanup\dac.py", line 623, in _runI2C
    read = [b & I2C_RB for b in data]
exceptions.NameError: global name 'I2C_RB' is not defined
 [payload=None]
```

**Comment by cjneill** [comment]
I2C_RB seems to be defined within the class - not sure why theres an issue. @DanielSank, @ejeffrey?

(FYI: Python version 2.6.4)
