### ISSUE TITLE
FPGA Error Message Unclear for Board not in BoardGroups

### ISSUE THREAD

**Issue by jwenner** [martinisgroup/servers#99]
We tried to run fpgaTest.average (which calls fpga.run_sequence) with only the DAC (i.e., not the ADC) in boardGroups. When we did this, the error should be something about a board not in boardGroups. However, we instead got a timeout error and a labrad.types.Error.

The particular error message in the fpgaTest IPython session was:
```
In [15]: fpgaTest.average(s,cxn,3,True)
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-15-53c37bbfb41c> in <module>()
----> 1 fpgaTest.average(s,cxn,3,True)

C:\pyle\pyle\scripts\fpgaTest\fpgaTest.pyc in average(sample, cxn, reps, plot, n
ame, dacsAdcs)
   1086     fpga.daisy_chain(daisyChainList)
   1087     fpga.timing_order([adc['_id']])
-> 1088     data = fpga.run_sequence(reps, True)[0]
   1089     if plot:
   1090         plt.figure()

C:\pylabrad\labrad\client.pyc in __call__(self, *args, **kw)
     62         if wrap:
     63             future.addCallback(lambda resp: resp[0][1])
---> 64         return future.wait() if wait else future
     65
     66     # data to be loaded on demand

C:\pylabrad\labrad\backend.pyc in wait(self)
    397                 # If any Future in the queue fails,
    398                 # we immediately bail.
--> 399                 result.raiseException()
    400             else:
    401                 for func, args, kw in f.callbacks:

C:\Python27\lib\site-packages\twisted\python\failure.pyc in raiseException(self)


Error: (0) [GHz FPGAs] Remote Traceback (most recent call last):
  File "C:\pylabrad\labrad\server.py", line 262, in handleRequest
    result = yield setting.handleRequest(self, c.data, data)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1105, in
_inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in t
hrowExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\pylabrad\servers\GHzDACs\ghz_fpga_server.py", line 1449, in run_seque
nce
    timingOrder)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1105, in
_inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in t
hrowExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\pylabrad\servers\GHzDACs\ghz_fpga_server.py", line 729, in run
    yield self.recoverFromTimeout(runners, results)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1107, in
_inlineCallbacks
    result = g.send(result)
  File "C:\pylabrad\servers\GHzDACs\ghz_fpga_server.py", line 857, in recoverFro
mTimeout
    raise Exception('Recover from error failed')
exceptions.Exception: Recover from error failed
 [payload=None]

In [16]:
```
All the stuff printed in the ghz_fpga_server window was:
```
C:\pylabrad\servers\GHzDACs>ghz_fpga_server.py
2015-04-16 12:56:51-0700 [-] Log opened.
2015-04-16 12:56:51-0700 [-] Starting factory <__main__.FPGAServer instance at 0
x040F23F0>
2015-04-16 12:56:51-0700 [Uninitialized] connected to 127.0.0.1:7682
2015-04-16 12:56:51-0700 [ServerProtocol,client] GHz FPGAs starting...
2015-04-16 12:56:52-0700 [ServerProtocol,client] Refreshing client connection...

2015-04-16 12:56:52-0700 [ServerProtocol,client] Loading board group definitions
 from registry...
2015-04-16 12:56:52-0700 [ServerProtocol,client] Board group definitions loaded.

2015-04-16 12:56:52-0700 [ServerProtocol,client] Board group definitions ok.
2015-04-16 12:56:52-0700 [ServerProtocol,client] Adapter 'rottmayer_direct_ether
net' (port 3) does not exist. Group will not be added.
2015-04-16 12:56:52-0700 [ServerProtocol,client] Adapter 'Vince Direct Ethernet'
 (port 0) does not exist. Group will not be added.
2015-04-16 12:56:52-0700 [ServerProtocol,client] Adapter 'DR Direct Ethernet' (p
ort 1) does not exist. Group will not be added.
2015-04-16 12:56:52-0700 [ServerProtocol,client] Adapter 'santo_direct_ethernet'
 (port 0) does not exist. Group will not be added.
2015-04-16 12:56:52-0700 [ServerProtocol,client] Adapter 'ivan_direct_ethernet'
(port 0) does not exist. Group will not be added.
2015-04-16 12:56:52-0700 [ServerProtocol,client] Adapter 'runningman_direct_ethe
rnet' (port 1) does not exist. Group will not be added.
2015-04-16 12:56:52-0700 [ServerProtocol,client] Board groups to be added: set([
('hercules_direct_ethernet', 2L)])
2015-04-16 12:56:52-0700 [ServerProtocol,client] Board groups to be removed: set
([])
2015-04-16 12:56:52-0700 [ServerProtocol,client] Creating board group 'hercules'
: server='hercules_direct_ethernet', port=2
2015-04-16 12:56:53-0700 [ServerProtocol,client] Devices detected on board group
 'hercules':
2015-04-16 12:56:53-0700 [ServerProtocol,client]   hercules DAC 53
2015-04-16 12:56:53-0700 [ServerProtocol,client]   hercules ADC 1
2015-04-16 12:56:53-0700 [ServerProtocol,client] connecting to DAC board: 00:01:
CA:AA:00:35 (build #8)
2015-04-16 12:56:53-0700 [ServerProtocol,client] connecting to ADC board: 00:01:
CA:AA:01:01 (build #7)
2015-04-16 12:56:53-0700 [ServerProtocol,client] GHz FPGAs now serving
2015-04-16 12:57:02-0700 [ServerProtocol,client] Traceback (most recent call las
t):
2015-04-16 12:57:02-0700 [ServerProtocol,client] Failure: labrad.types.Error: (0
) Operation timed out [payload=None]
2015-04-16 12:57:02-0700 [ServerProtocol,client] RECOVERING FROM TIMEOUT
2015-04-16 12:57:02-0700 [ServerProtocol,client] 'executionCounter'
```

On branch 00d5ad5e77ec5f6dc8030fa0798d063b064bdc4f.

**Comment by DanielSank** [comment]
It looks a lot like you're doing something wrong with the timing order.

fpgaTest is a total mess at the moment. It is on my todo list to fix it up.
